version: 3
sources:
  - name: users-db-us-east-1
    engine: postgres
    connection:
      host: localhost
      port: 54321
      database: postgres
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  - name: users-db-us-west-1
    engine: postgres
    connection:
      host: localhost
      port: 54322
      database: postgres
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  - name: users-db-us-east-2
    engine: postgres
    connection:
      host: localhost
      port: 54323
      database: postgres
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
tables:
  - name: users
    schema: public
    columns:
      - user_id
      - first_name
      - last_name
      - email
      - gender
      - ip_address
      - is_active
  - name: transactions
    schema: public
    columns:
      - transaction_id
      - user_id
      - product_id
      - quantity
      - price
      - transaction_date
      - payment_method
      - shipping_address
      - order_status
      - discount_code
