name: Main CI Flow

on:
  push:
    branches:
      - main
      - gor*
  pull_request:
    branches:
      - main
      - gor*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.21.1]
        os: [linux]
        # os: [darwin, linux]
        arch: [arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod tidy

      # - name: Lint
      #   run: go install golang.org/x/lint/golint@latest && golint ./...

      - name: Build
        env:
          # GOOS: ${{ matrix.os }}
          # GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 1
        run: |
          CGO_ENABLED=1 CGO_LDFLAGS="-L/usr/lib" go build --ldflags="-extldflags=-static" -tags osusergo,netgo ./cmd/cli 
          echo "Built for $GOOS $GOARCH"
        # run: |
        #   go build -ldflags '-extldflags "-static"' -o output/${{ matrix.os }}_${{ matrix.arch }}/hyphadb ./cmd/cli 
        #   echo "Built for $GOOS $GOARCH"
          
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: hyphadb-${{ matrix.os }}-${{ matrix.arch }}
          path: output/${{ matrix.os }}_${{ matrix.arch }}/hyphadb