name: CI

on: pull_request

jobs:
  integration-tests:
    env:
      HYPHA_CONFIG_PATH: ./build/ci
      HYPHA_MODELS_PATH: ./build/ci
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Build Docker services (PG, MySQL, etc.)
      run: 
        docker compose -f build/ci/docker-compose.yaml up -d

    - name: Install dependencies
      run: go mod tidy

    - name: Lint
      run: go install golang.org/x/lint/golint@latest && golint ./...

    - name: Hypha build
      run: make build

    - name: Hypha validate test
      run: bin/hypha source validate

    - name: Hypha model build test
      run: bin/hypha model build
    
    - name: Hypha query test
      run: bin/hypha query -f json "select * from mysql_data_types_test;"

    - name: Shut down services
      if: always()
      run: docker compose -f build/ci/docker-compose.yaml down