name: CI Jobs
on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Query Endpoint
        run: |
          docker-compose -f .docker/docker-compose.yaml up -d
          curl -X POST -H "Content-Type: application/json" -d '{"query": "select * from users limit 3" }' http://localhost:5051/query
