name: CI

on: pull_request

jobs:
  integration-tests:
    env:
      HYPHA_CONFIG_PATH: ./build/ci
      HYPHA_MODELS_PATH: ./build/ci
      PG_USER: ${{ secrets.PG_USER }}
      PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Build Docker services (PG, MySQL, etc.)
      run: 
        docker compose -f build/ci/docker-compose.yaml up -d

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        go mod tidy

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Hypha build
      run: make build

    - name: Hypha test
      run: build/ci/integration-tests.sh

    - name: Shut down services
      if: always()
      run: docker compose -f build/ci/docker-compose.yaml down