name: CI

on:
  pull_request:
    branches:
      - '*'
      - '!main'

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker services (PG, MySQL, etc.)
      run: docker-compose -f ./build/ci/docker-compose.yaml up -d

    - name: Hypha validate test
      run: go run main.go source validate

    - name: Hypha model build test
      run: go run main.go model build
    
    - name: Hypha query test
      run: go run main.go query -f json "select * from mysql_data_types_test;"

    - name: Shut down services
      if: always()
      run: docker-compose down