name: CI Jobs
on:
  pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t hyphadb-api -f .docker/hyphadb.Dockerfile .
